FROM python:3.8.12-slim-buster

# needed for postgre lib
RUN apt update && apt -y install libpq-dev gcc

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install pika==1.3.1

ADD . /app/

WORKDIR /app/


RUN chmod +x Dockerfiles/entrypoint.queue.sh
