FROM python:3.8.12-slim-buster
ENV PYTHONUNBUFFERED=1

RUN apt update && apt -y install libpq-dev gcc

ADD Dockerfiles/requirements/requirements_celery.txt .

RUN pip install -r requirements_celery.txt

ADD . /app/

WORKDIR /app/

COPY entrypoint.beat.sh /entrypoint.beat.sh
RUN chmod +x /entrypoint.beat.sh
RUN /entrypoint.beat.sh
