FROM python:3.8.12-slim-buster
ENV PYTHONUNBUFFERED=1

RUN apt update && apt -y install libpq-dev gcc

ADD Dockerfiles/requirements/requirements_celery.txt .

RUN pip install -r requirements_celery.txt

ADD . /app/

WORKDIR /app/

RUN chmod +x Dockerfiles/entrypoint.celery.sh
