name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: docker login --username davitkv8 --password ${{ secrets.REGISTRY_PASSWORD }} ghcr.io

    - name: Build and push Docker images
      run: |
        docker-compose build
        
        docker tag app ghcr.io/davitkv8/app:${{ github.sha }}
        docker push ghcr.io/davitkv8/app:${{ github.sha }}

        docker tag queue ghcr.io/davitkv8/queue:${{ github.sha }}
        docker push ghcr.io/davitkv8/queue:${{ github.sha }}
        
        docker tag beat ghcr.io/davitkv8/beat:${{ github.sha }}
        docker push ghcr.io/davitkv8/beat:${{ github.sha }}
        
        docker tag postgres ghcr.io/davitkv8/postgres:${{ github.sha }}
        docker push ghcr.io/davitkv8/postgres:${{ github.sha }}
        
        docker tag redis ghcr.io/davitkv8/redis:${{ github.sha }}
        docker push ghcr.io/davitkv8/redis:${{ github.sha }}