name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: docker login --username davitkv8 --password ${{ secrets.REGISTRY_PASSWORD }} ghcr.io

    - name: Build and push Docker images
      run: |
        docker-compose build
        
        docker tag hire-learn_app ghcr.io/davitkv8/app:${{ github.sha }}
        docker push ghcr.io/davitkv8/app:${{ github.sha }}

        docker tag hire-learn_queue ghcr.io/davitkv8/queue:${{ github.sha }}
        docker push ghcr.io/davitkv8/queue:${{ github.sha }}
        
        docker tag hire-learn_beat ghcr.io/davitkv8/beat:${{ github.sha }}
        docker push ghcr.io/davitkv8/beat:${{ github.sha }}
        
        docker tag hire-learn_celery ghcr.io/davitkv8/celery:${{ github.sha }}
        docker push ghcr.io/davitkv8/celery:${{ github.sha }}